{% set name = "unicode-slugify" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicode-slugify-{{ version }}.tar.gz
  sha256: 25f424258317e4cb41093e2953374b3af1f23097297664731cdb3ae46f6bd6c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six
    - unidecode

test:
  imports:
    - slugify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/mozilla/unicode-slugify
  summary: A slug generator that turns strings into unicode slugs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
